const actionTypes = {
    ADD_LIST: 'ADD_LIST',
    DELETE_LIST: 'DELETE_LIST',
    RENAME_LIST: 'RENAME_LIST',
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    EDIT_ITEM: 'EDIT_ITEM',
    TOGGLE_ITEM: 'TOGGLE_ITEM',

    TOGGLE_CONFIRM_DELETE: 'TOGGLE_CONFIRM_DELETE',
    TOGGLE_DARK_THEME: 'TOGGLE_DARK_THEME'
};

export default actionTypes;